# Generated by Django 4.2.1 on 2023-05-19 08:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_app.category')),
            ],
        ),
        migrations.CreateModel(
            name='Issuance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(999999999)])),
                ('date_issued', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_app.department')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_app.product')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodity_app.staff')),
            ],
        ),
    ]
