# Generated by Django 4.2.1 on 2023-06-01 20:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity_app', '0002_alter_staff_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(9999999)]),
        ),
    ]
